# Generated by Django 2.2 on 2020-07-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_profiles_api', '0002_profolefeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfoleFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
