# Generated by Django 2.2 on 2020-07-31 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_profiles_api', '0003_auto_20200731_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
    ]
